---
title: "As Snippets"
author: "kittipos sirivongrungson"
date: '2022-05-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
here::i_am("dev/as.Rmd")
library(here)

```

```{r}
usethis::use_r("as")
rstudioapi::navigateToFile(here("tests/testthat/test-as.R"))
```


### As Snippets Tibble

```{r as_snippets_tbl}
as_snippets_tbl <- function(ls) {
  
  # Validate
  as_snippets_tbl_validate(ls)
  
  # If "scope" is not provided set to `NA`
  scope_ls <- purrr::map(ls, "scope")
  noscope_lgl <- purrr::map_lgl(scope_ls, is.null)
  scope_ls[noscope_lgl] <- NA_character_
  # If "description" is not provided set to `NA`
  desc_ls <- purrr::map(ls, "description")
  nodesc_lgl <- purrr::map_lgl(desc_ls, is.null)
  desc_ls[nodesc_lgl] <- NA_character_
  
  tbl <- tibble::tibble(
    snippet_name = names(ls),
    scope = as.character(scope_ls), # scope always length 1
    prefix = purrr::map(ls, "prefix"),
    body = purrr::map(ls, "body"),
    description = desc_ls
  )
  # Set Class
  new_snippets_tbl(tbl)
  
}

ls_ex <- list(
  hello = list(
    scope = "markdown",
    prefix = "hello",
    body = c("hello, there", "$0"),
    description = "Say Hello"
  ),
  world = list(
    prefix = "world",
    body = "Welcome to a new world!"
  )
) 

as_snippets_tbl(ls_ex) 
```

```{r}
as_snippets_tbl_validate <- function(ls) {
  
  # Validate List of List
  if(!(is.list(ls) && purrr::every(ls, is.list))){
    stop("`ls` must be a list containing list of snippets", call. = FALSE)
  } 
  # Element must has names
  not_valid_names <- any(is.null(names(ls)), names(ls) == "")
  if(not_valid_names) stop("Elements in `ls` must have names for `snippet_name`.", call. = FALSE)
  # Must has "prefix" and "body"
  has_prefix_n_body <- purrr::every(ls, ~all(c("prefix", "body") %in% names(.x)))
  if(!has_prefix_n_body) stop("Snippets must contain 'prefix' and 'body' fields.", call. = FALSE)
  
  ls
  
}

as_snippets_tbl_validate(ls_ex)
```


### Helper: Flatten list if elements is Length 1 (Not In USE)

```{r flat_chr_if_len1}
flat_chr_if_len1 <- function(x) {
  
  stopifnot(is.list(x))
  # Check if every elements of list has length 1
  elements_len1 <- all(purrr::map_int(x, length) == 1L)
  
  if(elements_len1) {
    purrr::flatten_chr(x)
  } else {
    x
  }
}

flat_chr_if_len1(list("a", "b", NA))
flat_chr_if_len1(list("a", c("b", "c")))
```


```{r}
list("a", "b", NA) %>% map_int(length)

list("a", "b", NA) %>% flatten_chr()
list("a", c("b", "c")) %>% flatten_chr()
```



```{r}
names(list(1:2, c("a")))
names(list(a = 1:2, c("a")))

any(is.null(name(ls)), names(ls) == "")


purrr::map(ls_ex, names)
purrr::every(ls_ex, ~all(c("prefix", "body") %in% names(.x)))

purrr::map(ls_ex, "scope") %>% map_lgl(is.null)
purrr::map(ls_ex, "scope")[c(F, T)]
purrr::map(ls_ex, "description")
purrr::map_chr(ls_ex, "scope")
```





