---
title: "Read VS Code Snippet"
author: "kittipos sirivongrungson"
date: '2022-05-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file()) # Set WD to Root
here::i_am("dev/read-vs.Rmd")
library(here)

```

## Path of VS Code files

```{r path_vs}
path_vs <- snipper::snipper_example("vscode", return_path = T)
```

```{r path_vs_meet}
path_vs_meet <- snipper::snipper_example("vscode/meet.code-snippets")
```

```{r path_vs_r}
path_vs_r <- snipper::snipper_example("vscode/r.code-snippets")
```


## Read from JSON to Tibble

```{r}
usethis::use_r("vscode-read")
rstudioapi::navigateToFile(here("tests/testthat/test-vscode-read.R"))
```

### Try Read VS Code Snippet

```{r}
snipper::read_vscode_snippets(path_vs)
```


### Read JSON to Tibble (Wrapper)

```{r read_vscode_snippets}
read_vscode_snippets <- function(paths, 
                                 recurse = FALSE,
                                 regexp = "\\.(code-snippets)|(json)$",
                                 ...
                                 ) {
  
  if(!all(fs::file_exists(paths))) stop("`paths` must point to files or directory.", call. = F)
  # Get File Paths
  is_files <- fs::is_file(paths)
  files_chr <- names(is_files[is_files])
  # Get Dir Paths
  is_dir <- fs::is_dir(paths)
  dir_chr <- names(is_dir[is_dir])
  # Combine to Absolute file paths
  dir_files <- fs::dir_ls(dir_chr, recurse = recurse, regexp = regexp, ...)
  abs_paths <- c(files_chr, dir_files)
  
  tbl <- read_vscode_snippets_files(abs_paths)
  # Add "snippets_tbl" subclass
  new_snippets_tbl(tbl)
}

read_vscode_snippets(c("inst/extdata/vscode/meet.code-snippets"))
read_vscode_snippets(c(path_vs_meet))
read_vscode_snippets(c(path_vs, path_vs_meet)) #%>% class()
```



```{r}
fs::is_dir(c("dev",path_vs, "NAMESPACE", path_vs_meet))
fs::is_file(c("dev",path_vs, "NAMESPACE", path_vs_meet))
fs::file_exists(c("dev",path_vs, "NAMESPACE", path_vs_meet))
```

```{r}
fs::dir_ls(glob = c("*.md"))
fs::dir_ls(regexp = "\\.(md)|(Rproj)$")
```


```{r}
is_dir_ex1 <- fs::is_dir(c("dev",path_vs, "NAMESPACE", path_vs_meet))
is_dir_ex1
names(is_dir_ex1[is_dir_ex1]) %>% fs::dir_ls()
```


### Read Multiple Files

```{r read_vscode_snippets_files}
read_vscode_snippets_files <- function(files) {
  
  # Validate All `files` must be files
  stopifnot(all(fs::is_file(files)))
  
  file_names <- fs::path_file(files)
  names(files) <- file_names
  
  purrr::map_dfr(files, ~as_snippets_tbl(jsonlite::fromJSON(.x)), 
                 .id = "file_name")
  
}

read_vscode_snippets_files(fs::dir_ls(path_vs))
read_vscode_snippets_files(fs::dir_ls(path_vs)) %>% class()
# read_vscode_snippets_files(path_vs) # Error
```

### Read Single File (DEPRECATED)

```{r read_vscode_snippets_file}
read_vscode_snippets_file <- function(file) {
  
  ls_raw <- jsonlite::fromJSON(file)
  as_snippets_tbl(ls_raw)
  
}

read_vscode_snippets_file(path_vs_meet)
```

