---
title: "S3 OOP"
author: "kittipos sirivongrungson"
date: '2022-05-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
here::i_am("dev/s3.Rmd")
library(here)

```


```{r}
usethis::use_r("s3")
```

## Class: `snippets_list` ?

Possibly to provide constructor to user ??

### New: `snippets_list` ?

```{r new_snippets_list}
new_snippets_list <- function(x = list()){
  stopifnot(is.list(x))
  if(inherits(x, "snippets_list")) return(x)
  
  class(x) <- c("snippets_list", class(x))
  x
}

new_snippets_list(list(a = 1))
```

```{r}
l <- list(
  hello = list(
    scope = "markdown",
    prefix = "hello",
    body = c("hello, there", "$0"),
    description = "Say Hello"
  )
)

l_snp <- new_snippets_list(l)
l_snp
```

```{r}
# Subset will lost class
class(l_snp[1])
class(l_snp$hello)

# Append will also lost class
append(l_snp, list(world = "hi")) %>% class()
append(l_snp, l_snp) %>% class()
```


## Class: `snippets_tbl`


### New: `snippets_tbl`

```{r new_snippets_tbl}
new_snippets_tbl <- function(x = tibble::tibble()) {
  
  stopifnot(inherits(x, "tbl_df"))
  if(inherits(x, "snippets_tbl")) return(x) # Already Has Class
  
  class(x) <- c("snippets_tbl", class(x))
  x
}

new_snippets_tbl(tibble(x = 1:2)) %>% class()
```

