---
title: "Example of Read & Write VS Code Snippets"
author: "kittipos sirivongrungson"
date: '2022-05-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
here::i_am("dev/vs-readwrite.Rmd")
library(here)
library(jsonlite)
library(dplyr)
library(tibble)
```

### Planning

Object Naming Convention

`{editor}_snippetName_{R.obj}`

## Basic VS Code Snippets

### Read from JSON to List

```{r vs_hello_ls}
vs_hello_ls <- jsonlite::fromJSON(
  here("snippets/vscode-snippets/.vscode/hello.code-snippets")
  )
```


```{r}
class(vs_hello_ls)
vs_hello_ls
```

### Convert to Tibble (1 row)


```{r vs_hello_tbl}
vs_hello_tbl <- tibble(
  snippet_name = "hello",
  scope = vs_hello_ls$hello["scope"],
  prefix = vs_hello_ls$hello["prefix"], 
  body = vs_hello_ls$hello["body"], 
  description =  vs_hello_ls$hello["description"]
)

vs_hello_tbl
```


```{r}
as.list(vs_hello_tbl)

toJSON(vs_hello_tbl, pretty = TRUE) # Not right
```




#### Howto: List in tibble of snippets

```{r}
tibble(
  snippet_name = "hello",
  scope = "markdown,plaintext",
  prefix = list(prefix = c("hi", "hel")),
  body = list(body = c("Hello", "World", "$0")),
  description = list(description = c("Say Hello to the world", "Again"))
)
```




#### How to store list in a tibble 

```{r}
tibble(
  a = "A",
  b = list(B = c("B", "C")),
  c = list(C = c("D", "E", "F"))
) %>% 
  pull(b)
```


### Convert to JSON

```{r vs_hello_json}
vs_hello_json <- toJSON(vs_hello_ls, pretty = TRUE) 

class(vs_hello_json)
sloop::otype(vs_hello_json)
vs_hello_json
```





### Write JSON file

```{r}
vs_hello_json %>% 
  writeLines(here("snippets/vscode-snippets/.vscode/hello-out.code-snippets"))
```

And test that written snippet manually
